project_id = "zjtqptljuggbymcoovey"
[functions.upload-to-hfs]
verify_jwt = false
[functions.paystack-webhook]
verify_jwt = false
[functions.fund-wallet-paystack]
verify_jwt = true
[functions.withdraw-to-bank]
verify_jwt = true
[functions.check-investment-windows]
verify_jwt = false
[functions.mint-tokens-for-closed-window]
verify_jwt = false
[functions.distribute-tokens-to-kyc-users]
verify_jwt = false
[functions.create-proposal]
verify_jwt = true
[functions.send-chat-system-message]
verify_jwt = false
[functions.create-maintenance-proposal]
verify_jwt = true
[functions.create-property-treasury]
verify_jwt = false
[functions.auto-process-rental-dividends]
verify_jwt = false
[functions.process-scheduled-dividends]
verify_jwt = false
[functions.generate-investment-documents]
verify_jwt = false
[functions.handle-token-transfer]
verify_jwt = true